### ISSUE TITLE
Ableton 9.7 issue (and solution)

### ISSUE THREAD

**Issue by hgorelick** [genekogan/ofxAbletonLive#5]
LiveOSC doesn't show up in control devices. This fix seems to work.

comment out the following lines in socket_live8.py it works fine (assuming you're not using secure sockets)
```
# if _have_ssl:
# _realssl = ssl
# def ssl(sock, keyfile=None, certfile=None):
# if hasattr(sock, "_sock"):
# sock = sock._sock
# return _realssl(sock, keyfile, certfile)
```

From
http://livecontrol.q3f.org/ableton-liveapi/liveosc/

**Comment by genekogan** [comment]
yes, thanks, i know of this fix and have it documented in [https://github.com/ml4a/ml4a-ofx/tree/master/osc-modules/AbletonOSC](https://github.com/ml4a/ml4a-ofx/tree/master/osc-modules/AbletonOSC) but not here. the fix has been added.
